###
### R Script to extract the 5' and 3' regions adjacent to HBV sequences.
### for subqsequent chimera mapping.
###
library(Rsamtools)

### function extractsoftclip
extractsoftclip<-function(inbam,outfq){
aln <- scanBam(inbam)
print(outfq)
aln[[1]]$cigar -> cigar
cigarRangesAlongQuerySpace(cigar, ops="S") -> cigarir

### separate the pos and negative strand and 5' and 3' end
aln[[1]]$cigar[which(aln[[1]]$strand=="+")]->positivecigar
aln[[1]]$qname[which(aln[[1]]$strand=="+")]->positiveqname
names(positivecigar)<-positiveqname
cigarRangesAlongQuerySpace(positivecigar, ops="S",drop.empty.ranges=T) -> cigarir
startclip<-list()
endclip<-list()
for(i in 1:length(cigarir)){
cigarir[[i]][which(end(cigarir[[i]])==aln[[1]]$qwidth[i])]->endclip[[i]]
cigarir[[i]][which(start(cigarir[[i]])==1)]->startclip[[i]]
}

##### do positive start
aln[[1]]$seq[which(aln[[1]]$strand=="+")]->positiveseq
mylist<-list()
for(i in 1:length(startclip)){
extractAt(positiveseq[i],startclip[[i]])->mylist[[i]]
}

test2<-vector()
for(i in 1:length(mylist)){
length(mylist[[i]][[1]])->test2[i]
}

aln[[1]]$qname[which(aln[[1]]$strand=="+")]->positiveqname
positiveqname[which(test2>0)]-> positiveqname2
mylist[which(test2>0)]->mylist2
LargeDNAStringSet <- DNAStringSet(sapply(sapply(mylist2, `[[`, 1),"[[",1))
positiveqname2->names(LargeDNAStringSet)
print("Positive start file generated")
writeXStringSet(LargeDNAStringSet, paste("data/",outfq,".positive.start.fastq",sep=""), append=FALSE,compress=FALSE, compression_level=NA, format="fastq")

### do positive end
aln[[1]]$seq[which(aln[[1]]$strand=="+")]->positiveseq
mylist<-list()
for(i in 1:length(endclip)){
extractAt(positiveseq[i],endclip[[i]])->mylist[[i]]
}

test2<-vector()
for(i in 1:length(mylist)){
length(mylist[[i]][[1]])->test2[i]
}
aln[[1]]$qname[which(aln[[1]]$strand=="+")]->positiveqname
positiveqname[which(test2>0)]-> positiveqname2
mylist[which(test2>0)]->mylist2
LargeDNAStringSet <- DNAStringSet(sapply(sapply(mylist2, `[[`, 1),"[[",1))
positiveqname2->names(LargeDNAStringSet)
print("Positive end file generated")
writeXStringSet(LargeDNAStringSet, paste("data/",outfq,".positive.end.fastq",sep=""), append=FALSE,compress=FALSE, compression_level=NA, format="fastq")

#### do negative start
aln[[1]]$cigar[which(aln[[1]]$strand=="-")]->negativecigar
aln[[1]]$qname[which(aln[[1]]$strand=="-")]->negativeqname
names(negativecigar)<-negativeqname
cigarRangesAlongQuerySpace(negativecigar, ops="S",drop.empty.ranges=T) -> cigarir
startclip<-list()
endclip<-list()
for(i in 1:length(cigarir)){
cigarir[[i]][which(end(cigarir[[i]])==aln[[1]]$qwidth[i])]->endclip[[i]]
cigarir[[i]][which(start(cigarir[[i]])==1)]->startclip[[i]]
}
aln[[1]]$seq[which(aln[[1]]$strand=="-")]->negativeseq
mylist<-list()
for(i in 1:length(startclip)){
extractAt(negativeseq[i],startclip[[i]])->mylist[[i]]
}
test2<-vector()
for(i in 1:length(mylist)){
length(mylist[[i]][[1]])->test2[i]
}
aln[[1]]$qname[which(aln[[1]]$strand=="-")]->negativeqname
negativeqname[which(test2>0)]-> negativeqname2
mylist[which(test2>0)]->mylist2
LargeDNAStringSet <- DNAStringSet(sapply(sapply(mylist2, `[[`, 1),"[[",1))
negativeqname2->names(LargeDNAStringSet)
print("Negative start file generated")
writeXStringSet(LargeDNAStringSet, paste("data/",outfq,".negative.start.fastq",sep=""), append=FALSE,compress=FALSE, compression_level=NA, format="fastq")

### do negative end
aln[[1]]$seq[which(aln[[1]]$strand=="-")]->negativeseq
mylist<-list()
for(i in 1:length(endclip)){
extractAt(negativeseq[i],endclip[[i]])->mylist[[i]]
}
test2<-vector()
for(i in 1:length(mylist)){
length(mylist[[i]][[1]])->test2[i]
}
aln[[1]]$qname[which(aln[[1]]$strand=="-")]->negativeqname
negativeqname[which(test2>0)]-> negativeqname2
mylist[which(test2>0)]->mylist2
LargeDNAStringSet <- DNAStringSet(sapply(sapply(mylist2, `[[`, 1),"[[",1))
negativeqname2->names(LargeDNAStringSet)
print("Negative end file generated")
writeXStringSet(LargeDNAStringSet, paste("data/",outfq,".negative.end.fastq",sep=""), append=FALSE,compress=FALSE, compression_level=NA, format="fastq")}
### end of function extractsoftclip
###
### Start of main script to call extractsoftclip and generate fastq files.
###
print("Soft clip utility")
print(" ")
print("WARNING! This script is SLOW")
print("Probably best to start it off at the end of the day and collect in the morning...")
###
### read in the file barcodes
c("1002","1003","1004","1009","1010","1012","1013","1015")->all
###
### read bam file names and make calls to function.
for(i in 1:length(all)){
  ### read in the bam files generated by the shell script "align-script.sh"
  Bamname <- paste("data/",all[i],"_D3L.bam",sep="")
  print(Bamname)
  fqname <- all[i]
  extractsoftclip(Bamname,fqname)
} 
